# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-07 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default='')),
                ('celery_task_id', models.CharField(default='', max_length=500)),
                ('ready', models.BooleanField(default=False)),
                ('detail_area', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('plate_area', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('time_raspil', models.CharField(default='', max_length=200)),
                ('detail_count', models.IntegerField(default=0)),
                ('plate_count', models.IntegerField(default=0)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rez_length', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('kromka_04', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('kromka_08', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('kromka_20', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('page_count', models.IntegerField(default=0)),
                ('work_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость работы')),
                ('edge_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('depth', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Толщина')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeWorkCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('depth', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Толщина')),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('depth', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Толщина')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MaterialWorkCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_d', models.IntegerField(verbose_name='От')),
                ('max_d', models.IntegerField(verbose_name='До (не включая)')),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Заявка'), (1, 'Подтвержден'), (2, 'Выполняется'), (3, 'Выполнен'), (4, 'Выдан')], default=0, verbose_name='Статус')),
                ('info', models.CharField(max_length=1000, verbose_name='Информация о заказе')),
                ('calculation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel2.Calculation', verbose_name='Калькуляция')),
            ],
        ),
        migrations.AddField(
            model_name='calculation',
            name='edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel2.Edge', verbose_name='Кромка'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel2.Material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
